version: "3.8"
services:
  backend:
    container_name: technical-test-backend
    build: .
    restart: always
    ports:
      - "5050:5050"
    environment:
      - PORT=5050
      - NODE_ENV=development
      - JWT_SECRET_KEY=JWT_SECRET_KEY
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules